### ISSUE TITLE
Status Code: 400 No @context is provided for the resource

### ISSUE THREAD

**Issue by scenaristeur** [assemblee-virtuelle/semapps#303]
lorsque je tente un POST avec du turtle sur http://127.0.0.1:3000/resources

```
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .
@prefix ex: <http://example.org/stuff/1.0/> .

<http://www.w3.org/TR/rdf-syntax-grammar>
  dc:title "RDF/XML Syntax Specification (Revised)" ;
  ex:editor [
    ex:fullname "Dave Beckett";
    ex:homePage <http://purl.org/net/dajobe/>
  ] .
```

j'ai une erreur 

```
Status Code: 400 No @context is provided for the resource http://localhost:3000/resources/5ee133032823c37429b1b734
```

et dans la console semapps 
```
[2020-06-10T19:22:43.715Z] INFO  smag-8936/API: => POST /
[2020-06-10T19:22:43.721Z] INFO  smag-8936/API:    Call custom function in '  POST /resources => <Function>' alias
[2020-06-10T19:22:43.724Z] INFO  smag-8936/API:    Call 'ldp.resource.api_post' action
MoleculerError: No @context is provided for the resource http://localhost:3000/resources/5ee133032823c37429b1b734
    at Service.handler (C:\Users\Smag\Documents\dev\semapps-server\node_modules\@semapps\ldp\services\resource\actions\post.js:66:15)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Service.api (C:\Users\Smag\Documents\dev\semapps-server\node_modules\@semapps\ldp\services\resource\actions\post.js:10:27)
    at async Service.callAction (C:\Users\Smag\Documents\dev\semapps-server\node_modules\moleculer-web\src\index.js:616:16)
    at async C:\Users\Smag\Documents\dev\semapps-server\node_modules\moleculer-web\src\index.js:443:22 {
  code: 400,
  type: 'BAD_REQUEST',
  data: undefined,
  retryable: false
}
[2020-06-10T19:22:43.905Z] INFO  smag-8936/API: <= 400 POST /resources [+190.143 ms]
```

**Comment by simonLouvet** [comment]
coucou @scenaristeur , on va traité ce bug dans ce sprint normalement

**Comment by scenaristeur** [comment]
Cool, ensuite je réessaierai de me plugger dessus 👍
