### ISSUE TITLE
webfinger broken because activitypub.actor.get is not registered

### ISSUE THREAD

**Issue by s-ol** [assemblee-virtuelle/semapps#537]
**Décrivez le bug**
It seems that `@semapps/webfinger` is broken because `activitypub.actor.get` was removed at some point since 0.1.15, which is the version the molecular installer uses.

```
mol $ call webfinger.get '{ "resource": "acct:s-ol@tun.s-ol.nu" }'
>> Call 'webfinger.get' with params: { resource: 'acct:s-ol@tun.s-ol.nu' }
[2021-01-27T17:19:46.431Z] WARN  virek-86976/BROKER: Service 'activitypub.actor.get' is not registered.
>> Execution time:2ms
>> Response:
undefined

mol $ call activitypub.actor.get
>> Call 'activitypub.actor.get' with params: {}
[2021-01-27T17:25:48.300Z] WARN  virek-86976/BROKER: Service 'activitypub.actor.get' is not registered.
>> ERROR:
ServiceNotFoundError: Service 'activitypub.actor.get' is not found.
    at ServiceBroker.findNextActionEndpoint (/home/s-ol/Documents/other/fedidag/backend/node_modules/moleculer/src/service-broker.js:1025:13)
    at ServiceBroker.call (/home/s-ol/Documents/other/fedidag/backend/node_modules/moleculer/src/service-broker.js:1074:26)
    at call (/home/s-ol/Documents/other/fedidag/backend/node_modules/moleculer-repl/src/commands/call.js:88:9)
    at CommandInstance.<anonymous> (/home/s-ol/Documents/other/fedidag/backend/node_modules/moleculer-repl/src/commands/call.js:144:27)
    at Session.session.execCommandSet (/home/s-ol/Documents/other/fedidag/backend/node_modules/@moleculer/vorpal/dist/session.js:513:20)
    at Vorpal.vorpal._exec (/home/s-ol/Documents/other/fedidag/backend/node_modules/@moleculer/vorpal/dist/vorpal.js:1077:18)
    at Vorpal.vorpal._execQueueItem (/home/s-ol/Documents/other/fedidag/backend/node_modules/@moleculer/vorpal/dist/vorpal.js:852:17)
    at Vorpal.vorpal._queueHandler (/home/s-ol/Documents/other/fedidag/backend/node_modules/@moleculer/vorpal/dist/vorpal.js:835:10)
    at Vorpal.vorpal.exec (/home/s-ol/Documents/other/fedidag/backend/node_modules/@moleculer/vorpal/dist/vorpal.js:778:10)
    at /home/s-ol/Documents/other/fedidag/backend/node_modules/@moleculer/vorpal/dist/vorpal.js:722:10
    at /home/s-ol/Documents/other/fedidag/backend/node_modules/@moleculer/vorpal/dist/ui.js:258:13
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
Data:  { action: 'activitypub.actor.get' }
```

## reproduction
- create a new project (`moleculer init assemblee-virtuelle/semapps-template-activitypub my-activitypub-server`)
- update all packages to the last version (0.1.41)
- create a user account
- get user info from webfinger

**Comment by srosset81** [comment]
Thanks, I will fix that soon.

**Comment by s-ol** [comment]
I'm very new to molecular and semapps, but it seems that the cause is that in 9896553eeea81011b827af2afee6cf98c4f5038c the `DbService` that implements `get` was removed.

**Comment by srosset81** [comment]
It is fixed by https://github.com/assemblee-virtuelle/semapps/pull/539 and in the latest version 0.1.42
Please beware that there is a breaking change (explained in the PR). There is a running issue https://github.com/assemblee-virtuelle/semapps/issues/508 to update the Moleculer templates with the latest versions.

**Comment by s-ol** [comment]
Thanks for the quick response!
