### ISSUE TITLE
Cannot find module 'cas'

### ISSUE THREAD

**Issue by simonLouvet** [assemblee-virtuelle/semapps#638]
**Décrivez le bug**
Au lancement de pair-ldp-server
```
middleware    | [2021-03-08T11:32:53.557Z] ERROR 8bf9a85be6d6-66/BROKER: Failed to load service '/main/boilerplates/pair-ldp-server/services/api.service.js' Error: Cannot find module 'cas'
middleware    | Require stack:
middleware    | - /main/packages/connector/node_modules/passport-cas2/lib/passport-cas.js
middleware    | - /main/packages/connector/node_modules/passport-cas2/lib/index.js
middleware    | - /main/packages/connector/CasConnector.js
middleware    | - /main/packages/connector/index.js
middleware    | - /main/boilerplates/pair-ldp-server/services/api.service.js
middleware    | - /main/boilerplates/pair-ldp-server/node_modules/moleculer/src/service-broker.js
middleware    | - /main/boilerplates/pair-ldp-server/node_modules/moleculer/index.js
middleware    | - /main/boilerplates/pair-ldp-server/node_modules/moleculer/bin/moleculer-runner.js
middleware    |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
middleware    |     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
middleware    |     at Module.require (internal/modules/cjs/loader.js:849:19)
middleware    |     at require (internal/modules/cjs/helpers.js:74:18)
middleware    |     at Object.<anonymous> (/main/packages/connector/node_modules/passport-cas2/lib/passport-cas.js:7:11)
middleware    |     at Module._compile (internal/modules/cjs/loader.js:956:30)
middleware    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
middleware    |     at Module.load (internal/modules/cjs/loader.js:812:32)
middleware    |     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
middleware    |     at Module.require (internal/modules/cjs/loader.js:849:19)
middleware    |     at require (internal/modules/cjs/helpers.js:74:18)
middleware    |     at Object.<anonymous> (/main/packages/connector/node_modules/passport-cas2/lib/index.js:4:11)
middleware    |     at Module._compile (internal/modules/cjs/loader.js:956:30)
middleware    |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
middleware    |     at Module.load (internal/modules/cjs/loader.js:812:32)
middleware    |     at Function.Module._load (internal/modules/cjs/loader.js:724:14) {
middleware    |   code: 'MODULE_NOT_FOUND',
middleware    |   requireStack: [ '/main/packages/connector/node_modules/passport-cas2/lib/passport-cas.js', '/main/packages/connector/node_modules/passport-cas2/lib/index.js', '/main/packages/connector/CasConnector.js', '/main/packages/connector/index.js', '/main/boilerplates/pair-ldp-server/services/api.service.js', '/main/boilerplates/pair-ldp-server/node_modules/moleculer/src/service-broker.js', '/main/boilerplates/pair-ldp-server/node_modules/moleculer/index.js', '/main/boilerplates/pair-ldp-server/node_modules/moleculer/bin/moleculer-runner.js' ]
middleware    | }
```

**Etapes pour reproduire**
make start

**Comportement attendu**
pas de platage

**Captures d'écran**
voir erreur ci dessus

**contournement**
middleware.packages.connector.index.js
```
module.exports = {
  Connector: require('./Connector'),
  //CasConnector: require('./CasConnector'),
  OidcConnector: require('./OidcConnector')
};
```

**Comment by fluidlog** [comment]
@simonLouvet @srosset81 toujours d'actualité depuis la revue de l'authentification ? (je peux tester si vous n'avez pas le temps...)

**Comment by simonLouvet** [comment]
je ne sais pas, à tester mais ca fait longtemps que j'a pas vu ce bug
