### ISSUE TITLE
[Branche Next] MoleculerError: Group already exists lors du redémarrage du middleware

### ISSUE THREAD

**Issue by VincentFarcy** [assemblee-virtuelle/semapps#898]
**Décrivez le bug**
Sur la branche next, lors d'un redémarrage du middleware, le docker-compose up plante.
Il faut supprimer le dossier data à chaque fois pour que ça passe.

**Etapes pour reproduire**
Branche next
docker-compose up middleware
=> ok
ctrl+c
docker-compose up middleware
=> plantage : 
```
middleware        | [2021-12-09T09:44:33.324Z] INFO  2240a03f07b8-74/WEBACL.GROUP: Super admin group doesn't exist, creating it...
middleware        | [2021-12-09T09:44:33.365Z] ERROR 2240a03f07b8-74/BROKER: Unable to start all services. MoleculerError: Group already exists
middleware        |     at Service.handler (/main/packages/webacl/services/group/actions/create.js:35:15)
middleware        |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
middleware        |     at async Service.started (/main/packages/webacl/services/group/index.js:46:30)
middleware        |     at async Promise.all (index 30) {
middleware        |   code: 400,
middleware        |   type: 'BAD_REQUEST',
middleware        |   data: undefined,
middleware        |   retryable: false
middleware        | }
middleware        | [Runner] Group already exists MoleculerError: Group already exists
middleware        |     at Service.handler (/main/packages/webacl/services/group/actions/create.js:35:15)
middleware        |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
middleware        |     at async Service.started (/main/packages/webacl/services/group/index.js:46:30)
middleware        |     at async Promise.all (index 30) {
middleware        |   code: 400,
middleware        |   type: 'BAD_REQUEST',
middleware        |   data: undefined,
middleware        |   retryable: false
middleware        | }
middleware        | npm ERR! code ELIFECYCLE
middleware        | npm ERR! errno 1
middleware        | npm ERR! pair-ldp-server@0.4.0-alpha.0 dev: `moleculer-runner --repl --hot services`
middleware        | npm ERR! Exit status 1
middleware        | npm ERR! 
middleware        | npm ERR! Failed at the pair-ldp-server@0.4.0-alpha.0 dev script.
middleware        | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
middleware        | 
middleware        | npm ERR! A complete log of this run can be found in:
middleware        | npm ERR!     /root/.npm/_logs/2021-12-09T09_44_33_403Z-debug.log
middleware exited with code 1
```

**Comment by nikoPLP** [comment]
C'est bon j'ai trouvé le bug. le fix est dans la branche next (Commit 2b561789)
il suffit de faire un
`git pull`.

ne pas oublier aussi de bien effacer tous les dataset et leur fichier de config, car les donnees sont corrompues par ce bug.

**Comment by VincentFarcy** [comment]
C'est ok merci !
